### ISSUE TITLE
Improper use of useCallback at pages/home/Map.jsx

### ISSUE THREAD

**Issue by akmalhazim** [harithzahid/mapbox-thousand-markers#5]
<img width="402" alt="image" src="https://user-images.githubusercontent.com/34267739/163809115-a38879d5-dc5c-4501-9b49-4bb428bd2c0a.png">

`getBounds` here is re-instantiated for every re-render. Therefore, `onMapLoad`, `onMapMoveEnd` won't benefit the memoized callback function. Just a slight improvement can be done, but overall great work!

**Comment by harithzahid** [comment]
Nice catch. Thanks for pointing it out!
